#!/bin/bash

echo "🚀 PARDNALINK TESTING - QUICK START"
echo "=================================="
echo ""
echo "❌ Server is currently DOWN"
echo ""
echo "🔧 TO START SERVER:"
echo "1. Go to AWS Console → EC2"
echo "2. Find instance: ip-10-0-1-213.ec2.internal"
echo "3. Start instance if stopped"
echo "4. Or SSH and restart:"
echo "   ssh -i ../pardnalink-keypair.pem ec2-user@52.23.203.107"
echo "   cd /home/ec2-user/digital-pardna-platform/backend"
echo "   pm2 restart all"
echo ""
echo "✅ WHEN SERVER IS UP, RUN:"
echo "./run-all-tests.sh     # All tests"
echo "./customer-tests.sh    # Customer only"
echo "./corporate-tests.sh   # Corporate only"
echo "./third-party-tests.sh # API only"
echo ""
echo "🔍 CHECK SERVER STATUS:"
echo "curl http://52.23.203.107:3001/v1/health"